name: Deploy App

on:
  push:
    branches:
      - main # Modify this to match your repository's default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Debug Private Key
        run: echo "$SSH_PRIVATE_KEY"

      - name: Debug SSH Command
        run: echo "ssh -o StrictHostKeyChecking=no ${{ secrets.USER_SERVER }}@${{ secrets.IP_SERVER }} './coding/hanafi-fiqh-app/deploy.sh'"

      - name: Setup SSH agent
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.HOST_SERVER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Use the private key for authentication
          port: 22
          script: |
            # Your Docker-related deployment commands here
            cd ./coding/hanafi-fiqh-app
            chmod +x deploy.sh
            ./deploy.sh


