name: Deploy App

on:
  workflow_run:
    workflows: ["Build App"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH agent
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.HOST_SERVER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Use the private key for authentication
          port: 22
          script: |
            # Your Docker-related deployment commands here
            cd ./coding/hanafi-fiqh-app
            
            # Stop the existing container (if running)
            docker stop hanafi-fiqh-app || true
            
            # Remove the existing container (if exists)
            docker rm hanafi-fiqh-app || true
            
            # Pull the latest Docker image from Docker Hub
            docker pull sahedw/hanafi-fiqh-app:latest
            
            # Start a new container with the updated image
            docker run -d --name hanafi-fiqh-app --env MONGO_DB_URI=${{ secrets.MONGO_DB_URI }} -p 8080:8080 sahedw/hanafi-fiqh-app:latest
