name: "Get Logs"

on:
  workflow_dispatch:

jobs:
  get-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Get logs from docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USER_SERVER }}
          password: ${{ secrets.ROOT_PASSWORD_SERVER }}
          script: |
            sudo docker logs hanafi-fiqh-app
